class MovieRunner {
    public static void main(String args[]) {
        Movie movie = new Movie();
        System.out.println(movie.getName());
        movie.setName("Inception");
        System.out.println(movie.getName());
        movie.setBudget(160000000.0f);
        System.out.println(movie.getBudget());
        movie.setMovieId(501);
        movie.setDirector("Christopher Nolan");
        System.out.println(movie.getDirector());
        movie.setRating(8.8f);
        System.out.println(movie.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(1500000.0f);
        System.out.println(Movie.getTax());

        Movie movie1 = new Movie();
        movie1.setName("Interstellar");
        System.out.println(movie1.getName());
        movie1.setBudget(165000000.0f);
        System.out.println(movie1.getBudget());
        movie1.setMovieId(502);
        movie1.setDirector("Christopher Nolan");
        System.out.println(movie1.getDirector());
        movie1.setRating(8.6f);
        System.out.println(movie1.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(1400000.0f);
        System.out.println(Movie.getTax());

        Movie movie2 = new Movie();
        movie2.setName("Avatar");
        System.out.println(movie2.getName());
        movie2.setBudget(237000000.0f);
        System.out.println(movie2.getBudget());
        movie2.setMovieId(503);
        movie2.setDirector("James Cameron");
        System.out.println(movie2.getDirector());
        movie2.setRating(7.8f);
        System.out.println(movie2.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(1800000.0f);
        System.out.println(Movie.getTax());

        Movie movie3 = new Movie();
        movie3.setName("Parasite");
        System.out.println(movie3.getName());
        movie3.setBudget(11400000.0f);
        System.out.println(movie3.getBudget());
        movie3.setMovieId(504);
        movie3.setDirector("Bong Joon-ho");
        System.out.println(movie3.getDirector());
        movie3.setRating(8.6f);
        System.out.println(movie3.getRating());
        Movie.setLanguage("Korean");
        System.out.println(Movie.getLanguage());
        Movie.setTax(500000.0f);
        System.out.println(Movie.getTax());

        Movie movie4 = new Movie();
        movie4.setName("Titanic");
        System.out.println(movie4.getName());
        movie4.setBudget(200000000.0f);
        System.out.println(movie4.getBudget());
        movie4.setMovieId(505);
        movie4.setDirector("James Cameron");
        System.out.println(movie4.getDirector());
        movie4.setRating(7.9f);
        System.out.println(movie4.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(1300000.0f);
        System.out.println(Movie.getTax());

        Movie movie5 = new Movie();
        movie5.setName("Dangal");
        System.out.println(movie5.getName());
        movie5.setBudget(70000000.0f);
        System.out.println(movie5.getBudget());
        movie5.setMovieId(506);
        movie5.setDirector("Nitesh Tiwari");
        System.out.println(movie5.getDirector());
        movie5.setRating(8.3f);
        System.out.println(movie5.getRating());
        Movie.setLanguage("Hindi");
        System.out.println(Movie.getLanguage());
        Movie.setTax(800000.0f);
        System.out.println(Movie.getTax());

        Movie movie6 = new Movie();
        movie6.setName("Joker");
        System.out.println(movie6.getName());
        movie6.setBudget(55000000.0f);
        System.out.println(movie6.getBudget());
        movie6.setMovieId(507);
        movie6.setDirector("Todd Phillips");
        System.out.println(movie6.getDirector());
        movie6.setRating(8.4f);
        System.out.println(movie6.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(1000000.0f);
        System.out.println(Movie.getTax());

        Movie movie7 = new Movie();
        movie7.setName("3 Idiots");
        System.out.println(movie7.getName());
        movie7.setBudget(55000000.0f);
        System.out.println(movie7.getBudget());
        movie7.setMovieId(508);
        movie7.setDirector("Rajkumar Hirani");
        System.out.println(movie7.getDirector());
        movie7.setRating(8.4f);
        System.out.println(movie7.getRating());
        Movie.setLanguage("Hindi");
        System.out.println(Movie.getLanguage());
        Movie.setTax(850000.0f);
        System.out.println(Movie.getTax());

        Movie movie8 = new Movie();
        movie8.setName("Avengers: Endgame");
        System.out.println(movie8.getName());
        movie8.setBudget(356000000.0f);
        System.out.println(movie8.getBudget());
        movie8.setMovieId(509);
        movie8.setDirector("Russo Brothers");
        System.out.println(movie8.getDirector());
        movie8.setRating(8.4f);
        System.out.println(movie8.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(2000000.0f);
        System.out.println(Movie.getTax());

        Movie movie9 = new Movie();
        movie9.setName("The Godfather");
        System.out.println(movie9.getName());
        movie9.setBudget(6000000.0f);
        System.out.println(movie9.getBudget());
        movie9.setMovieId(510);
        movie9.setDirector("Francis Ford Coppola");
        System.out.println(movie9.getDirector());
        movie9.setRating(9.2f);
        System.out.println(movie9.getRating());
        Movie.setLanguage("English");
        System.out.println(Movie.getLanguage());
        Movie.setTax(600000.0f);
        System.out.println(Movie.getTax());
    }
}
